apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
     app: backend_app
  ports:
  - port: {{ .Values.service.backendPort }}
    targetPort: {{ .Values.service.backendPort }}
