apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend_app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend_app
  template:
    metadata:
      labels:
        app: frontend_app
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.frontend }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
