apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: "/data"
  persistentVolumeReclaimPolicy: Retain
