replicaCount: 1

image:
  backend: nejibyaakoubi/backend:v4
  frontend: nejibyaakoubi/frontend_image
  mysql: mysql:5.6

mysql:
  rootPassword: "root"

service:
  backendPort: 8080
  frontendPort: 8080
  mysqlPort: 3306

ingress:
  enabled: true
  backendHost: server.devops.com
  frontendHost: client.devops.com

persistence:
  storageClass: manual
  accessMode: ReadWriteOnce
  size: 1Gi
